# Worker 名称
name = "cf-flux-remix"

# 兼容性日期，确保使用最新的 Workers 运行时功能
compatibility_date = "2024-10-04"

# 主入口文件
main = "./build/worker/index.js"

# 静态资源目录
assets = { directory = "./build/client" }

# 启用 Workers 日志
[observability]
enabled = true

# KV 命名空间配置
[[kv_namespaces]]
binding = "IMAGE_KV"
id = "528e12da11b1456b869cd0d43ac56bf4"
